all: tcpclient tcpserver udpclient udpserver

tcpclient:
	gcc -o tcpclient tcpclient.c

tcpserver:
	gcc -o tcpserver tcpserver.c

udpclient:
	gcc -o udpclient udpclient.c

udpserver:
	gcc -o udpserver udpserver.c

clean:
	rm -f tcpclient tcpserver udpclient udpserver